### ISSUE TITLE
Can not find Claims in seed user 

### ISSUE THREAD

**Issue by jerryho83** [PioneerCode/pioneer-blog#100]
Hi
Base on your code i uncomment code lin functions seed user but visual studio said that can not find any Claims method

![bbbbbbbbb](https://user-images.githubusercontent.com/20026010/31553705-85664084-b065-11e7-9772-bb94f72e649e.jpg)

In namespace i used like below

![issue2](https://user-images.githubusercontent.com/20026010/31553589-293c4042-b065-11e7-9e0b-a5178b91d76a.jpg)

Could you check why i can not find any method Claims?
Best

**Comment by chad-ramos** [comment]
@jerryho83 Once you have registered a new account at ../account/register, add the following to your claims table with the updated UserId. 
![claims](https://user-images.githubusercontent.com/3170200/32416536-32896e60-c210-11e7-9b10-3cedc7b84b3f.png)

I do not seed users and claims. 

Chad

**Comment by chad-ramos** [comment]
Update README with instructions on how to register and account.
