### ISSUE TITLE
How to write markdown post content?

### ISSUE THREAD

**Issue by Just1n** [PioneerCode/pioneer-blog#127]
![image](https://user-images.githubusercontent.com/517376/37407003-a18d82b4-27d3-11e8-802e-67daa1e57436.png)

**Comment by chad-ramos** [comment]
@Just1n Hi, currently pioneer-blog does not support markdown conversion(s).

**Comment by Just1n** [comment]
@chad-ramos So how to write a formatted post?
Like how to make a break line, how to paste some code, even some boldface characters?

**Comment by chad-ramos** [comment]
@Just1n Everything is done with HTML at the moment. You can enter HTML into that textarea, save it, and it will show up on the UI. 

I just updated the wiki with some more information.

[Creating Blog Posts](https://github.com/PioneerCode/pioneer-blog/wiki/Creating-Blog-Posts)

**Comment by chad-ramos** [comment]
@Just1n Please feel free to open a new issue if you have any more questions.
