### ISSUE TITLE
missing typings file

### ISSUE THREAD

**Issue by isaac2004** [PioneerCode/pioneer-blog#68]
When I run any gulp task, I get this error

> dev\admin\components\categories\main.ts(1,1): error TS6053: File 'C:/Users/IsaacLevin/Downloads/pioneer-blog-master/src/Pioneer.Blog/typings/index.d.ts' not found.
dev\admin\components\posts\main.ts(1,1): error TS6053: File 'C:/Users/IsaacLevin/Downloads/pioneer-blog-master/src/Pioneer.Blog/typings/index.d.ts' not found.
dev\admin\components\tags\main.ts(1,1): error TS6053: File 'C:/Users/IsaacLevin/Downloads/pioneer-blog-master/src/Pioneer.Blog/typings/index.d.ts' not found.
dev\public\app.ts(1,1): error TS6053: File 'C:/Users/IsaacLevin/Downloads/pioneer-blog-master/src/Pioneer.Blog/typings/index.d.ts' not found.
dev\public\app.ts(2,1): error TS2304: Cannot find name '$'.
dev\public\app.ts(3,3): error TS2304: Cannot find name '$'.
dev\public\app.ts(8,3): error TS2304: Cannot find name '$'.
dev\public\app.ts(14,14): error TS2304: Cannot find name '$'.
dev\public\app.ts(19,1): error TS2304: Cannot find name '$'.
dev\public\app.ts(31,1): error TS2304: Cannot find name '$'.

Looks like your typings file is missing from git

**Comment by chad-ramos** [comment]
@isaac2004 There is a `typings.json` that will generate the typings for you.  You need to run...
```bash
typings install
```
... to install the necessary assets. 

I have also updated the README with relevant info on how to set the project up.

Best,

Chad

**Comment by isaac2004** [comment]
Oh damn, for some reason I thought your install script generated that. Disregard :)
________________________________

**Comment by chad-ramos** [comment]
No problem...
