### ISSUE TITLE
where is the database ?

### ISSUE THREAD

**Issue by dmhai** [PioneerCode/pioneer-blog#74]
I can find /admin/app.css only，where is the /app.css and app.js?

**Comment by chad-ramos** [comment]
Hi @dmhai ,

- You need to run the EF migrations to produce your database.
- Client assets (/app.css & /app.js)
  - These are built using gulp. 
  - There is no reason to store built assets in the repository as they don't need to be versioned with the code. 
    - Instead, built assets should be produced prior to deployment and typically from a build server.
    - Take a look at the gulp-task folder to see the available gulp commands you can run.
 - /admin/app.css
   - This actually was never supposed to be pushed to the repo (see above), Thanks for drawing my attention to it.  :smiley:
   - I will be removing it from the repository. 
 
Best,

Chad
