### ISSUE TITLE
Task never defined: pubilc

### ISSUE THREAD

**Issue by dmhai** [PioneerCode/pioneer-blog#76]
It's error...

D:\src\Pioneer.Blog>gulp pubilc
[17:47:24] Using gulpfile D:\_Document\Desktop\pioneer-blog-master\src\Pioneer.Blog\gulpfile.js
[17:47:24] Task never defined: pubilc
[17:47:24] To list available tasks, try running: gulp --tasks

**Comment by chad-ramos** [comment]
Hi @dmhai,

Did you run npm install prior to trying to run this task?

Thanks,

Chad

**Comment by dmhai** [comment]
@chad-ramos yes  I  did , I run all the command  step by step, and result as this :

cd D:\src\Pioneer.Blog
	npm rm --global gulp 			(success)
	npm install gulp-cli -g			(success)
	npm install typings -g			(success)

	npm install					(success)
	npm rebuild node-sass --force	(success)
	typings install					(success)
	gulp pubilc 					(***error)
	gulp admin 					(***error)

**Comment by chad-ramos** [comment]
@dmhai - I attempted to reproduce this on a fresh install and was not able to.  Can you confirm you are running commands at '...pioneer-blog\src\Pioneer.Blog'.

Thanks,

Chad

**Comment by chad-ramos** [comment]
@dmhai 

I am closing this issue based on the last contact.

Best,

Chad
