### ISSUE TITLE
No bower.json present

### ISSUE THREAD

**Issue by jerryho83** [PioneerCode/pioneer-blog#77]
Hi
I run command line --->  bower install
I got the error:  no bower.json present
Please see the image attached more detail 
![Uploading blog.jpg…]()

**Comment by chad-ramos** [comment]
@jerryho83 I dropped bower (being it is deprecated) in favor of pulling all packages from npm.  When I did such, I failed to update the [README](https://github.com/PioneerCode/pioneer-blog/blob/master/README.md).  It is updated now.  

Thanks,

Chad

**Comment by chad-ramos** [comment]
Closing based on README being updated...
