### ISSUE TITLE
PasswordHasher adn AppConfiguration are never assigned

### ISSUE THREAD

**Issue by digounet** [PioneerCode/pioneer-blog#83]
Hello,

I'm havin an issue with uour _passwordHasher and _appConfiguration properties. They are always null. You are not injecting it anywhere.

**Comment by chad-ramos** [comment]
@digounet 

Please provide more information on what you are trying to accomplish.  Currently, I have not run into the issue you are describing.  Configuration is parsed and added to the IOC container via the `startup.cs` class.

Best,

Chad

**Comment by digounet** [comment]
Sorry, it's working. A little mistake mine.
