### ISSUE TITLE
Forbidden in admin

### ISSUE THREAD

**Issue by jerryho83** [PioneerCode/pioneer-blog#84]
@chad-ramos 
When i tried to create new post/category and tags in admin.I got the error below

![blog](https://user-images.githubusercontent.com/20026010/29196784-f62edbc8-7e60-11e7-923b-277aa33b6164.jpg)

Please see 3 tables in my database,user,role and user role below

![user](https://user-images.githubusercontent.com/20026010/29196915-bc21656c-7e61-11e7-867b-ada61a08bcf2.jpg)

![roles](https://user-images.githubusercontent.com/20026010/29196928-d1959d0a-7e61-11e7-9cae-408103269f75.jpg)

![useroles](https://user-images.githubusercontent.com/20026010/29196932-d8014dec-7e61-11e7-93e6-740cfa7044fe.jpg)

Best 
 Jerry

**Comment by chad-ramos** [comment]
@jerryho83 Sorry for the delay, add the following claim. 

![image](https://user-images.githubusercontent.com/3170200/29337655-b4ca0d7c-81d7-11e7-9034-8ea5abc48fa3.png)

**Comment by chad-ramos** [comment]
@jerryho83 If you have any more question regarding this, please submit a new issue. 

Thanks,

Chad
