### ISSUE TITLE
Duplicate code 

### ISSUE THREAD

**Issue by jerryho83** [PioneerCode/pioneer-blog#98]
Hi @chad-ramos : 
I found your code like 

```
 getAll(): Promise<Category[]> {
    return this.http.get(this.url)
      .toPromise()
      .then((res: Response) => {
        const body: Category[] = res.json();
        return body || [];
      })
      .catch(this.handleError);
  }

  create(): Promise<Category> {
    return this.http.post(this.url, {} as Category)
      .toPromise()
      .then((res: Response) => {
        const body: Category = res.json();
        return body || [];
      })
      .catch(this.handleError);
  }
```
then you can see this repeat many times in your code
```
 .then((res: Response) => {
        const body: Category = res.json();
        return body || [];
```
I think the better create function like this
```
private extractData(res: Response) {
        let body = res.json();
        return body || {};
    }
```
then we can use like this

```
  getAll(): Promise<Category[]> {
    return this.http.get(this.url)
      .toPromise()
      .then(this.extractData)
      .catch(this.handleError);
  }
```
Please let me know about that idea
Best Jerry

**Comment by chad-ramos** [comment]
@jerryho83 Fully agree with you.  I am currently working on a small rewrite in the admin section.  Of which, this will be addressed in. 

Thanks,

Chad

**Comment by chad-ramos** [comment]
@jerryho83 Realized something after review this.  Look at the types being returned.  One returns an object and the other returns an array.  The proposed solution does not work across all extractions in the categories class.
